name: Rust Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Tests ${{ matrix.name }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux / stable
          - name: linux / beta
            rust: beta
              # - name: macOS / stable
              #   os: macOS-latest
              # TODO: Support windows
              # - name: windows / stable-x86_64-gnu
              # os: windows-latest
              # rust: stable-x86_64-pc-windows-gnu
              # target: x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust || 'stable' }}
          targets: ${{ matrix.target }}
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          brew install docker-buildx
      - name: Test docker
        run: docker run hello-world
      - name: Check
        run: cargo check
      - name: Test
        run: cargo test -- --test-threads=1 --nocapture